[imap]
server = "mail.diesels.co.za"
port = 993
tls = true

[cache]
folder = "./cache"

# Optional sections - will use defaults if not specified
[jwt]
secret = "your-custom-jwt-secret"

[encryption]
key = "your-custom-32-byte-encryption-key"


[ssl]
enabled = true
cert_file = "/etc/letsencrypt/live/yourdomain.com/fullchain.pem"
key_file = "/etc/letsencrypt/live/yourdomain.com/privkey.pem"
port = 443
http_port = 80
auto_redirect = true
domain = "yourdomain.com"
hsts_max_age = 31536000  # 1 year in seconds