# config/default.toml

[server]
host = "localhost"
port = 8080
tls = true

[cache]
directory = "cache"
max_size = 1024  # Maximum cache size in MB
ttl = "24h"      # Cache TTL
cleanup_every = "1h"  # Cleanup interval

[security]
key_directory = "keys"
session_timeout = "12h"
max_login_attempts = 5
rate_limit_window = "15m"

[folders]
exclude_folders = ["Spam", "Trash"]
max_concurrent = 5
batch_size = 50

# Email provider configurations can be added here
[[providers]]
domain = "example.com"
imap_server = "imap.example.com"
imap_port = 993
smtp_server = "smtp.example.com"
smtp_port = 587